binaries = [ "modprobe", "lsmod" ]

kmod_pull_firmware = true

[custom_parameters]
kernel_modules = "NoDupFlatList"  # Kernel modules to pull into the initramfs
kernel_version = "str"  # Kernel version to use for the initramfs
kmod_pull_firmware = "bool"  # Whether or not to pull firmware for kernel modules
kmod_ignore_softdeps = "bool"  # Whether or not softdeps are ignored
kmod_init = "NoDupFlatList"  # Kernel modules to load at initramfs startup
kmod_autodetect_lsmod = "bool"  # Whether or not to automatically pull currently loaded kernel modules
kmod_autodetect_lspci = "bool"  # Whether or not to automatically pull kernel modules from lspci -k
kmod_ignore = "NoDupFlatList"  # Kernel modules to ignore when loading
_kmod_removed = "NoDupFlatList"  # Meant to be used internally, defines kernel modules which have been ignored at runtime
_kmod_modinfo = "dict" # Used internally, caches modinfo output for kernel modules

[imports.config_processing]
"ugrd.kmod.kmod" = [ "_process_kmod_init_multi", "_process_kmod_ignore_multi" ]

[imports.build_pre]
"ugrd.kmod.kmod" = [ "calculate_modules", "process_modules", "process_module_metadata" ]

[imports.init_pre]
"ugrd.kmod.kmod" = [ "load_modules" ]
