kmod_ignore = [
'rfkill', 'bluetooth', 'cfg80211', 'mac80211', # Wireless
'iwlwifi', 'iwlmvm', 'btusb', 'btintel', 'btrtl', 'btbcm', 'btmtk',  # wireless vendor
'cdc_ether', 'stp', '8021q', 'llc', 'garp', 'mrp', 'bridge', 'bonding',  # Ethernet
'r8169', 'r8152', 'r8153_ecm', 'igb', 'ixgbe', 'tg3', 'e1000e', 'e1000',  # Ethernet cards
'tun', 'tap', 'wireguard', 'udp_tunnel', 'ip6_udp_tunnel',  # Tunnels
'net_failover', 'failover','vhost_net','usbnet',  # Misc
'tls', 'sctp',  # Misc protocols
'grace', 'nfs_acl', 'nfsd', 'lockd', 'sunrpc', 'auth_rpcgss', 'nfs', 'netfs',  # NFS
'nf_nat', 'nfnetlink', 'nfnetlink_queue', 'nfnetlink_log',  # Netfilter base
'nf_conntrack', 'nf_conntrack_netlink',  # Netfilter conntrack
'nf_defrag_ipv4', 'nf_defrag_ipv6',  # Netfilter defrag
'nf_reject_ipv4', 'nf_reject_ipv6',  # Netfilter reject
'iptable_filter', 'ip_tables', 'ip6table_filter', 'ip6_tables',   # iptables
'xt_MASQUERADE', 'xt_conntrack', 'xt_CHECKSUM', 'xt_addrtype', 'xt_comment', 'xt_conntrack', 'xt_mark', 'xt_multiport', 'xt_nat', 'xt_recent', 'xt_set', 'xt_tcpudp', 'xt_u32',  # iptables extensions
'ip6table_nat', 'iptable_nat', 'iptable_mangle', 'ip6table_mangle',  # iptables nat/mangle
'ipt_REJECT', 'ip6t_REJECT'  # iptables reject
]
