kmod_ignore = ['snd_hda_intel', 'snd', 'soundcore', 'ledtrig_audio', 'snd_intel_sdw_acpi', 'snd_rawmidi', 'snd_seq_dummy',
	       'snd_hda_codec', 'snd_seq_device', 'snd_hrtimer', 'snd_hwdep', 'snd_usbmidi_lib', 'snd_pcm', 'snd_hda_codec_hdmi',
	       'snd_timer', 'snd_usb_audio', 'snd_hda_core', 'snd-seq-device', 'snd_seq', 'snd_intel_dspcfg', 'pcspkr',
	       'snd-rawmidi', 'snd_ump']
