modules = [
  "ugrd.base.base",
  "ugrd.base.console",
  "ugrd.crypto.gpg",
  "ugrd.crypto.cryptsetup",
  "ugrd.base.btrfs"
]

key_type = "gpg"

[root_mount.source]
label = "rootfs"

[console.ttyS1]
baud = 115_200
type = "vt100"
local = true

[mounts.boot]
type = "vfat"

  [mounts.boot.source]
  uuid = "4A48-F4DC"

[cryptsetup.root1]
uuid = "9e04e825-7f60-4171-815a-86e01ec4c4d3"
key_file = "/boot/keys/crypt1.gpg"

[cryptsetup.root2]
uuid = "37b8e5ad-e855-4248-b93d-23df30c6e6aa"
key_file = "/boot/keys/crypt2.gpg"
