# This module generates an initramfs that uses a yubikey to decrypt a luks keyfile.
# The sc_public_key must be specified.


modules = [
  "base_modules.base",
  "base_modules.kmod",
  "base_modules.cryptsetup",
  "base_modules.btrfs",
  "base_modules.serial",
  "base_modules.gpg",
  "base_modules.smartcard"
]

out_dir = "/usr/src/initramfs"
clean = true
sc_public_key = "/home/larry/yubikey_public.asc"

# Different modules will be required on different systems. Only modules needed to mount the root are required.
kernel_modules = [ 'nvme', 'uas', 'vfat', 'dm_crypt' ]

# This is only necessary if the keyfile is on another device.
# The keyfile could be added as a dependency.
[mounts.boot]
type = "vfat"

  [mounts.boot.source]
  uuid = "4886-A631"

# The label of the volume under the LUKS partition, a UUID could be used
[root_mount]
label = "rootfs"

# Information about the LUKS volume
[root_devices.crypt]
uuid = "eee3611d-9b36-42b3-8ed2-62173064c76a"
key_type = "gpg"
key_file = "/boot/rootfs.luks.gpg"
