# This config will decrypt the colume fdf442da-0574-4531-98c7-55227a041f1d, mapping it to "/dev/mapper/root"
# It will attempt to mount the btrfs subvolume "gento" from the devive with label "rootfs" to /root
# It will pull all current kernel modules from the active kernel version
# The kmod.novideo and kmod.nosound modules are pulled to help minmize pulled modules


modules = [
  "ugrd.base.base",
  "ugrd.kmod.kmod",
  "ugrd.kmod.novideo",
  "ugrd.kmod.nosound",
  "ugrd.crypto.cryptsetup",
]

# Optionally supply a kernel version
#kernel_version = "6.1.53-gentoo-dist"
kmod_autodetect_lsmod = true

[mounts.root]
type = "btrfs"
options = ["subvol=gentoo"]

[mounts.root.source]
label = "rootfs"

# The UUID of the encrypted volume, mounted at /dev/mapper/root
[cryptsetup.root]
uuid = "fdf442da-0574-4531-98c7-55227a041f1d"
