modules = [
  "base_modules.base",
  "base_modules.kmod",
  "base_modules.cryptsetup",
  "base_modules.gpg",
  "base_modules.btrfs"
]
out_dir = "/usr/src/initramfs"
clean = true
#kernel_modules = ['dm_crypt', 'amdgpu', 'edac_mce_amd', 'uvcvideo', 'kvm_amd', 'uvc', 'videobuf2_vmalloc', 'drm_suballoc_helper', 'videobuf2_memops', 'amdxcp', 'videobuf2_v4l2', 'iommu_v2', 'kvm', 'gpu_sched', 'videobuf2_common',
#                  'irqbypass', 'vfat', 'fat', 'uas', 'nvme_core', 'nvme', 'nvme_common', 'video' ]

key_type = "gpg"
gpg_public_key = "/etc/dracut.conf.d/crypt-public-key.gpg"

[mounts.boot]
type = "vfat"

  [mounts.boot.source]
  uuid = "4182-B466"


[root_mount]
label = "rootfs"
uuid = "3dd3a76c-910e-4ab8-bdc4-710d381765ce"

[root_devices.crypt]
uuid = "96636938-b518-4103-8693-8b8f2d305ecd"
key_file = "/boot/2t.luks.gpg"
