
modules = [
  "ugrd.base.base",
  "ugrd.base.kmod",
  "ugrd.base.plymouth",
  "ugrd.base.btrfs",
]

out_dir = "/usr/src/initramfs"

# Optionally supply a kernel version
#kernel_version = "6.1.53-gentoo-dist"

[root_mount.source]
label = "rootfs"

# The UUID of the encrypted volume, mounted at /dev/mapper/root
[cryptsetup.root]
uuid = "fdf442da-0574-4531-98c7-55227a041f1d"
