# Config to mount a zfs rootfs called rpool with gpg keyfiles in /mnt/usb/root.luks.gpg

modules = [
  "ugrd.base.base",
  "ugrd.base.kmod",
  "ugrd.crypto.cryptsetup",
  "ugrd.base.zfs",
  "ugrd.base.console",
  "ugrd.crypto.gpg",
]

#out_dir = "/usr/src/initramfs"

#kernel_version = "6.5.6-gentoo-initramfs"
kmod_init = ['nvme', 'uas', 'fat' ]

mount_wait = true
mount_timeout = 2

[mounts.usb]
type = "vfat"
destination = "/mnt/usb"

  [mounts.usb.source]
  uuid = "4182-B466"

[root_mount.source]
label = "rpool"

[cryptsetup.root]
uuid = "3ffbb856-ac38-495e-bf8d-2a0fb7faf47f"
key_type = "gpg"
key_file = "/mnt/usb/root.luks.gpg"
