modules = [
  "base_modules.base",
  "base_modules.cryptsetup",
  "base_modules.btrfs"
]
out_dir = "/usr/src/initramfs"
clean = true

[root_mount]
label = "rootfs"
uuid = "3dd3a76c-910e-4ab8-bdc4-710d381765ce"

[root_devices.crypt]
uuid = "96636938-b518-4103-8693-8b8f2d305ecd"
