# This config will decrypt the LUKS volume with uuid "fdf442da-0574-4531-98c7-55227a041f1d", mapping it to "/dev/mapper/root"
# It will attempt to mount the btrfs volume with label "rootfs" to /mnt/root
# It will pull all current kernel modules from the active kernel version
# The "ugrd.base.kmod_nvme" module will be used to load the nvme module if it's not detected in lsmod
# The "ugrd.base.cpio" module will pack the initramfs into a cpio archive

modules = [
  "ugrd.base.base",
  "ugrd.base.kmod",
  "ugrd.base.kmod_nvme",
  "ugrd.crypto.cryptsetup",
  "ugrd.base.btrfs",
  "ugrd.base.cpio",
]

# The initramfs will be built in /tmp/initramfs if "build_dir" is not specified not specified
out_dir = "/usr/src/initramfs"  # Output here instead of /tmp/initramfs_out

# Optionally supply a kernel version, uses the current kernel version if not specified
#kernel_version = "6.1.53-gentoo-dist"
kmod_autodetect = true

# Create device nodes only inside the CPIO
mknod_cpio = true

[root_mount.source]
# The lable of the root filesystem, a uuid could be used instead
label = "rootfs"

# The UUID of the encrypted volume, mounted at /dev/mapper/root
[cryptsetup.root]
uuid = "fdf442da-0574-4531-98c7-55227a041f1d"
