modules = [
  "base_modules.base",
  "base_modules.cryptsetup",
  "base_modules.btrfs",
  "base_modules.kmod"
]

out_dir = "/usr/src/initramfs"
clean = true

[root_mount]
label = "rootfs"
uuid = "d36ce220-298a-4600-8b0d-0183bd577452"

[root_devices.crypt]
uuid = "9e04e825-7f60-4171-815a-86e01ec4c4d3"
