# This config will decrypt the colume fdf442da-0574-4531-98c7-55227a041f1d, mappint it to "crypt"
# It will attempt to mount the btrfs volume with label "rootfs" to /root
# It will pull all current kernel modules from the active kernel version


modules = [
  "base_modules.base",
  "base_modules.cryptsetup",
  "base_modules.btrfs",
  "base_modules.kmod"
]

out_dir = "/usr/src/initramfs"
clean = true

[mounts.boot]
type = "vfat"

  [mounts.boot.source]
  uuid = "1234-ABCD"


[root_mount]
label = "rootfs"

[root_devices.crypt]
uuid = "fdf442da-0574-4531-98c7-55227a041f1d"
key_file = "/boot/crypt_key.luks"
