# This config will decrypt the colume fdf442da-0574-4531-98c7-55227a041f1d, mappint it to "crypt"
# It will attempt to mount the btrfs volume with label "rootfs" to /root
# It will pull all current kernel modules from the active kernel version


modules = [
  "ugrd.base.base",
  "ugrd.crypto.cryptsetup",
  "ugrd.base.btrfs",
  "ugrd.base.kmod"
]

out_dir = "/usr/src/initramfs"
clean = true
# Optionally supply a kernel version
#kernel_version = "6.1.53-gentoo-dist"


[root_mount]
label = "rootfs"

# The UUID of the encrypted volume, mounted at /dev/mapper/root
[cryptsetup.root]
uuid = "fdf442da-0574-4531-98c7-55227a041f1d"
