modules = [ "ugrd.crypto.gpg" ]

binaries = [ "/usr/libexec/scdaemon" ]

kmod_init = "uhid"
cryptsetup_autoretry = false

[cryptsetup_key_types.gpg]
reset_command = "{ gpgconf --reload && gpg --card-status }"

[custom_parameters]
sc_public_key = "Path"  # The path to the public key to import

[imports.config_processing]
"ugrd.crypto.smartcard" = [ "_process_sc_public_key" ]

[imports.init_early]
"ugrd.crypto.smartcard" = [ "import_keys" ]

