modules = [ "ugrd.crypto.gpg" ]

binaries = [ "/usr/libexec/scdaemon" ]

kmod_init = "uhid"
cryptsetup_autoretry = false

[cryptsetup_key_types.gpg]
# Escape braces as .format() is used
reset_command = '{{ gpgconf --reload && einfo "$(gpg --card-status)"; }}'

[custom_parameters]
sc_public_key = "Path"  # The path to the public key to import

[imports.config_processing]
"ugrd.crypto.smartcard" = [ "_process_sc_public_key" ]

[imports.init_main]
"ugrd.crypto.smartcard" = [ "import_keys" ]

[import_order.after]
import_keys = "start_agent"
