modules = ["ugrd.base.core", "ugrd.base.cmdline", "ugrd.fs.mounts", "ugrd.kmod.kmod", "ugrd.fs.cpio"]

binaries = [ "awk", "grep", "ls", "cp", "cat", "switch_root" ]

paths = [ "root" ]

shebang = "#!/bin/bash -l"
switch_root_target = "/mnt/root"
autodetect_init = true

[imports.config_processing]
"ugrd.base.base" = [ "_process_switch_root_target", "_process_init_target", "_process_autodetect_init" ]

[imports.init_premount]
"ugrd.base.base" = [ "export_switchroot_target" ]

[imports.init_final]
"ugrd.base.base" = [ "export_init_target", "do_switch_root" ]

[imports.functions]
"ugrd.base.base" = [ "check_var", "setvar", "readvar", "edebug", "einfo", "ewarn", "_find_init" ]

[custom_parameters]
init_target = "Path"  # Specifies the location of the system init file
autodetect_init = "bool"  # If set to true, the init_target will be autodetected based on the system's init system
shebang = "str"  # Add the shebang property, used because this is a bash script
switch_root_target = "str"  # Add the switch_root_target property, used to specify the target directory for switch_root. Sets the default target for the root mount
