modules = ["ugrd.base.core", "ugrd.fs.mounts", "ugrd.fs.cpio"]

binaries = [ "awk", "grep", "ls", "cp", "cat", "switch_root" ]

paths = [ "root" ]

shebang = "#!/bin/bash"

[imports.config_processing]
"ugrd.base.base" = [ "_process_switch_root_target" ]

[imports.init_premount]
"ugrd.base.base" = [ "export_switchroot_target" ]

[imports.init_final]
"ugrd.base.base" = [ "do_switch_root" ]

[custom_parameters]
shebang = "str"  # Add the shebang property, used because this is a bash script
switch_root_target = "str"  # Add the switch_root_target property, used to specify the target directory for switch_root overriding the root mount destination
