modules = [ "ugrd.base.core",
	    "ugrd.fs.mounts",
	    "ugrd.base.cmdline",
	    "ugrd.kmod.kmod",
	    "ugrd.fs.cpio",
	    "ugrd.base.checks" ]

binaries = [ "awk", "grep", "ls", "cp", "cat", "switch_root" ]

paths = [ "root" ]

shebang = "#!/bin/bash -l"
autodetect_init = true

[imports.config_processing]
"ugrd.base.base" = [ "_process_init_target", "_process_autodetect_init" ]

[imports.build_pre]
"ugrd.base.base" = [ "autodetect_init" ]

[imports.init_final]
"ugrd.base.base" = [ "do_switch_root" ]

[imports.functions]
"ugrd.base.base" = [ "check_var", "setvar", "readvar", "prompt_user",
                     "edebug", "einfo", "ewarn", "eerror",
		     "rd_fail", "rd_restart", "_find_init" ]

[custom_parameters]
init_target = "Path"  # Specifies the location of the system init file
autodetect_init = "bool"  # If set to true, the init_target will be autodetected based on the system's init system
shebang = "str"  # Add the shebang property, used because this is a bash script
