check_included_funcs = true

[imports.tests]
"ugrd.base.check" = ["run_checks"]

[custom_parameters]
check_included_funcs = 'bool'  # Checks that all included functions are in the profile
check_in_file = 'dict'  # Dict where each key is a file, and the value is a list of strings to look for in a file
