[imports.init_pre]
"ugrd.base.cmdline" = [ "parse_cmdline" ]

[imports.init_mount]
"ugrd.base.cmdline" = [ "mount_cmdline_root" ]

[imports.functions]
"ugrd.base.cmdline" = [ "parse_cmdline_bool", "parse_cmdline_str" ]

[custom_parameters]
_init_mount = "NoDupFlatList" # List contaning functions which were removed from imports.int_mount by refactor_mounts
