mod_depends = ['ugrd.base.base']

[imports.init_early]
"ugrd.base.cmdline" = [ "parse_cmdline" ]

[imports.init_mount]
"ugrd.base.cmdline" = [ "mount_cmdline_root" ]

[masks]
init_mount = [ "mount_root" ]

# Import this function to be used by mount_cmdline_root
[imports.functions]
"ugrd.fs.mounts" = [ "mount_root" ]
