[imports.init_pre]
"ugrd.base.cmdline" = [ "export_exports", "parse_cmdline" ]

[imports.init_mount]
"ugrd.base.cmdline" = [ "mount_cmdline_root" ]

[imports.functions]
"ugrd.base.cmdline" = [ "parse_cmdline_bool", "parse_cmdline_str" ]

[custom_parameters]
exports = "dict"  # Add the exports property, used to specify the exports for the init script
_init_mount = "NoDupFlatList" # List contaning functions which were removed from imports.int_mount by refactor_mounts
