binaries = [ "agetty" ]

# Define the primary console
primary_console = "tty0"

[console.tty0]
type = "tty"

[imports.custom_init]
"ugrd.base.console" = [ "custom_init" ]

[custom_parameters]
console = "dict"  # Contains console configuration
primary_console = "str"  # Contains the primary console device
