binaries = [ "agetty" ]
_custom_init_file = "init_main.sh"

[imports.custom_init]
"ugrd.base.console" = [ "custom_init" ]

[custom_parameters]
console = "dict"  # Contains console configuration
primary_console = "str"  # Contains the primary console device
