out_file = "ugrd.cpio"
mknod_cpio = true

[imports.config_processing]
"ugrd.base.cpio" = [ "_process_out_file" ]

[imports.pack]
"ugrd.base.cpio" = [ "make_cpio" ]

[custom_parameters]
out_file =  "str"  # The name of the cpio file to create.
mknod_cpio = "bool"  # When enabled, mknod is not used to create device nodes, they are just created in the cpio.
