binaries = ['cp', 'mv', 'rm', 'find', 'grep', 'dmesg', 'chmod', 'touch']
dependencies = [ "/usr/share/terminfo/l/linux" ] # required by most editors
# EDITOR is determined at build time using (in order):
# 1. editor config parameter
# 2. $EDITOR environment variable
# 3. fallback to 'nano'

start_shell = true

[imports.build_enum]
"ugrd.base.debug" = [ "detect_editor" ]

[imports.init_pre]
"ugrd.base.debug" = [ "enable_debug" ]

[imports.init_debug]
"ugrd.base.debug" = [ "start_shell" ]

[custom_parameters]
start_shell = "bool"  # Start a shell after init_early, before init_pre. Can be enabled by the debug cmdline option.
editor = "str"  # override editor variable
no_validate_editor = "bool"  # will skip validation of the editor binary, when validation is in use. Otherwise does nothing.
