binaries = ['plymouthd', 'plymouth', 'plymouth-set-default-theme']

dependencies = ['/usr/share/plymouth/plymouthd.defaults',
		'/usr/share/plymouth/themes/text/text.plymouth',
                '/usr/share/plymouth/themes/details/details.plymouth']

[imports.config_processing]
"ugrd.base.plymouth" = [ "_process_plymouth_config", "_process_plymouth_theme" ]

[mounts.devpts]
type = "devpts"
destination = "/dev/pts"
options = ['noauto', 'nosuid', 'noexec', 'rw', 'mode=620', 'gid=5']
no_validate_options = true
path = "devpts"

[imports.build_pre]
"ugrd.base.plymouth" = [ "find_plymouth_config" ]

[imports.build_tasks]
"ugrd.base.plymouth" = [ "pull_plymouth" ]

[imports.init_early]
"ugrd.base.plymouth" = [ "make_devpts", "start_plymouth" ]

[custom_parameters]
plymouth_config = "Path"  # Path to the plymouth configuration file
plymouth_force_splash = "bool"  # Hardcode the splash argument into the plymouthd fake kernel cmdline
plymouth_theme = "str"  # Name of the plymouth theme to use
