shebang = "#!/bin/bash"

binaries = [
  "bash",
  "ls",
  "cat",
  "lsblk",
  "blkid",
  "mount",
  "umount",
  "switch_root"
]

paths = [
  "bin",
  "boot",
  "dev",
  "etc",
  "lib",
  "lib64",
  "mnt/root",
  "root",
  "sbin",
  "sys"
]

[imports.config_processing]
"base_modules.base" = [ "_process_mounts_multi" ]

[imports.build_tasks]
"base_modules.base" = [ "generate_fstab" ]

[imports.init_pre]
"base_modules.base" = [ "mount_fstab" ]

[imports.init_late]
"base_modules.base" = [ "mount_root" ]

[imports.init_final]
"base_modules.base" = [ "clean_mounts", "switch_root" ]

[custom_parameters]
shebang = "str"  # Add the shebang property, used because this is a bash script
mounts = "dict"  # Add the mounts property, used to define the mounts to be made in the fstab
out_dir = "str"  # Add the out_dir property, used to define the output directory
clean = "bool"  # Add the clean property, used to define if the mounts should be cleaned up after boot
root_mount = "dict"  # Add the root_mount property, used to define the root mount

# Define the default mounts
# The format is mounts.mount where the mount is the name of the mount
# Alternatively, the destination option can be used to define the mount point

[mounts.proc]
type = "proc"
source = "proc"

[mounts.sys]
type = "sysfs"
source = "sysfs"

[mounts.dev]
type = "devtmpfs"
source = "devtmpfs"
