binaries = [ "cryptsetup" ]
paths = [ "usr/lib64", "run" ]
kernel_modules = [ "dm_crypt" ]  # This should warn if the kmod module is not being used, but this is not strictly required


[imports.init_pre]
"base_modules.cryptsetup" = [ "configure_library_dir" ]

[imports.init_late]
"base_modules.cryptsetup" = [ "crypt_init" ]

[imports.build_tasks]
"base_modules.cryptsetup" = [ "copy_libgcc" ]

[custom_parameters]
root_devices = "dict"  # Dict of root devices, keyed by device name
key_type = "str"  # Type of key to use for unlocking, can be set for each device
