binaries = [ "ln", "gpg", "gpg-agent", "gpg-connect-agent", "pinentry-tty", "tty", "/usr/libexec/scdaemon" ]
paths = [ "usr/bin" ]

# GPG works best under agetty for input
depends = [ "base_modules.serial" ]
primary_console = "tty0"

[imports.init_pre]
"base_modules.gpg" = [ "symlink_pinentry" ]

[imports.init_main]
"base_modules.gpg" = [ "start_agent" ]

[serial.tty0]
type = "tty"

