binaries = [ "agetty" ]

[imports.custom_init]
"base_modules.serial" = [ "custom_init" ]

[custom_parameters]
serial = "dict"  # Contains serial port entries
primary_console = "str"  # Contains the primary console device
