# This configuration should autodetect root/luks info and use detached headers

modules = [
  "ugrd.kmod.standard_mask",
  "ugrd.crypto.cryptsetup"
]

auto_mounts = ['/boot']  # Automatically create mount config for /boot on the host

[cryptsetup.root]
header_file = "/boot/luks_header.img"
