# This example config demonstrates how kmod autodetection/masking can be configured

# By default all kmod categories are ignored
kmod_ignore_video = true
kmod_ignore_sound = true
kmod_ignore_network = true

# Optionally supply a kernel version, uses the current kernel version if not specified
#kernel_version = "6.1.53-gentoo-dist"
# Get host modules using lspci and lsmod
kmod_autodetect_lspci = true
kmod_autodetect_lsmod = true
