# This module generates an initramfs that decrypts a passphrase protected LUKS keyslot
# Automatically pull current kmods
# Don't pull sound, video, or network kmods

modules = [
  "ugrd.crypto.cryptsetup",
  "ugrd.kmod.nosound",
  "ugrd.kmod.novideo",
  "ugrd.kmod.nonetwork",
]

kmod_autodetect_lsmod = true


# Information about the LUKS volume
[cryptsetup.root]
uuid = "eee3611d-9b36-42b3-8ed2-62173064c76a"
