# This config will decrypt the volume fdf442da-0574-4531-98c7-55227a041f1d, mapping it to "/dev/mapper/root"
# It will attempt to mount the btrfs subvolume "gentoo" from the device with label "rootfs" to /root
# It will pull kernel modules based on the hardware detected by lspci
# The kmod novideo, nosound, and nonetwork modules will be used to restrict the kernel modules pulled


modules = [
  "ugrd.kmod.novideo",
  "ugrd.kmod.nosound",
  "ugrd.kmod.nonetwork",
  "ugrd.crypto.cryptsetup",
  "ugrd.fs.btrfs",
]

# Optionally supply a kernel version
#kernel_version = "6.1.53-gentoo-dist"
kmod_autodetect_lspci = true

root_subvol="gentoo"

# The UUID of the encrypted volume, mounted at /dev/mapper/root
[cryptsetup.root]
uuid = "fdf442da-0574-4531-98c7-55227a041f1d"
