# This config will pull kmods required for VMs to boot
# Commented config will decrypt the volume with UUID "38a5c4d2-f5af-404a-a663-d789e443a40c", mapping it to /dev/mapper/root

modules = [
  "ugrd.kmod.vm",
#  "ugrd.crypto.cryptsetup",
]

# Optionally supply a kernel version
#kernel_version = "6.1.57-gentoo-custom"

# The UUID of the encrypted volume, mounted at /dev/mapper/root
#[cryptsetup.root]
#uuid = "38a5c4d2-f5af-404a-a663-d789e443a40c"
