modules = ["ugrd.base.core", "ugrd.fs.mounts", "ugrd.base.cpio"]

binaries = [ "grep", "ls", "cat", "switch_root" ]

paths = [ "root" ]

shebang = "#!/bin/bash"

[imports.init_final]
"ugrd.base.base" = [ "do_switch_root" ]

[custom_parameters]
shebang = "str"  # Add the shebang property, used because this is a bash script
