shebang = "#!/bin/bash"

modules = ["ugrd.base.core", "ugrd.fs.mounts"]

binaries = [ "bash", "ls", "cat", "switch_root" ]

paths = [ "root" ]

[imports.init_final]
"ugrd.base.base" = [ "switch_root" ]

[custom_parameters]
shebang = "str"  # Add the shebang property, used because this is a bash script

