file_owner = "portage"
build_dir = "/tmp/initramfs"
out_dir = "/tmp/initramfs_out"
clean = true
hostonly = true
library_paths = [ "/lib64" ]
old_count = 1

binaries = [ "bash" ]

[nodes.console]
mode = 0o644
major = 5
minor = 1

[imports.config_processing]
"ugrd.base.core" = [ "_process_binaries_multi",
		     "_process_dependencies_multi",
		     "_process_copies_multi",
		     "_process_symlinks_multi",
		     "_process_file_owner",
		     "_process_nodes_multi",
		     "_process_paths_multi",
		   ]

[imports.build_pre]
"ugrd.base.core" = [ "clean_build_dir" ]

[imports.build_tasks]
"ugrd.base.core" = [ "generate_structure", "deploy_dependencies", "deploy_copies", "deploy_nodes", "deploy_symlinks" ]

[imports.init_pre]
"ugrd.base.core" = [ "configure_library_paths" ]

[custom_parameters]
binaries = "NoDupFlatList"  # Binaries which should be included in the intiramfs, dependencies resolved with lddtree
dependencies = "NoDupFlatList"  # Add the dependencies property, used to define the dependencies of the initramfs
library_paths = "NoDupFlatList"  # Add the library_paths property, used to define the library paths to add to LD_LIBRARY_PATH
symlinks = "dict"  # Add the symlinks property, used to define the symlinks to be made in the initramfs
copies = "dict"  # Add the copies property, used to define the files to be copied to the initramfs
nodes = "dict"  # Add the nodes property, used to define the device nodes to be created
paths = "NoDupFlatList"  # Paths to be copied to the initramfs
build_dir = "Path"  # The directory where the initramfs is built
out_dir = "Path"  # The directory where the initramfs is packed/output. If no packer is used, this is the final output directory.
old_count = "int"  # The number of times to cycle old files before deleting
clean = "bool"  # Add the clean property, used to define if the mounts should be cleaned up after boot
hostonly = "bool"  # If true, the initramfs will be designed for the host creating it
file_owner = "str"  # Add the file_owner property, used to define who should own the copied initramfs files
_file_owner_uid = "int"  # Add the _file_owner_uid property, used to store the uid of the file owner
_custom_init_file = "str"  # Add the _custom_init_file propety, used to set where the custom init file is located

