cpio_filename = "ugrd.cpio"
cpio_list_name = "cpio.list"

[imports.pack]
"ugrd.base.cpio" = [ "make_cpio_list", "pack_cpio" ]

[custom_parameters]
mknod_cpio = "bool"  # When enabled, mknod is not used to create device nodes, they are just created in the cpio.
cpio_filename = "str"  # The name of the cpio file to create.
cpio_list_name = "str"  # The name of the CPIO packing list to create
_gen_init_cpio_path = "Path"  # The path of the gen_init_cpio binary
