binaries = [ "modprobe" ]


[custom_parameters]
kernel_modules = "NoDupFlatList"  # Kernel modules to pull into the initramfs
kernel_version = "str"  # Kernel version to use for the initramfs
kmod_init = "NoDupFlatList"  # Kernel modules to load at initramfs startup
kmod_ignore = "NoDupFlatList"  # Kernel modules to ignore when loading

[imports.build_pre]
"ugrd.base.kmod" = [ "fetch_modules" ]

[imports.init_pre]
"ugrd.base.kmod" = [ "load_modules" ]
