binaries = [ "modprobe", "lsmod" ]

[custom_parameters]
kernel_modules = "NoDupFlatList"  # Kernel modules to pull into the initramfs
kernel_version = "str"  # Kernel version to use for the initramfs
kmod_ignore_softdeps = "bool"  # Whether or not softdeps are ignored
kmod_init = "NoDupFlatList"  # Kernel modules to load at initramfs startup
kmod_ignore = "NoDupFlatList"  # Kernel modules to ignore when loading
_kmod_depend = "NoDupFlatList"  # Meant to be used internally, defines kernel modules to automatically load, typically within other module config


[imports.config_processing]
"ugrd.base.kmod" = [ "_process_kmod_init_multi" ]

[imports.build_pre]
"ugrd.base.kmod" = [ "calculate_modules" ]

[imports.init_pre]
"ugrd.base.kmod" = [ "load_modules" ]
