
binaries = ['plymouthd', 'plymouth']

paths = ['/run/plymouth']

[mounts.devpts]
type = "devpts"
destination = "/dev/pts"
source = "/dev/pts"
remake_mountpoint = true

[imports.build_pre]
"ugrd.base.plymouth" = [ "populate_initrd" ]

[imports.init_main]
"ugrd.base.plymouth" = [ "start_plymouth" ]
