binaries = [ "btrfs" ]
kmod_init = [ "btrfs", "crc32c" ] # crc32c is a softdep but more or less required

_base_mount_path = "/root_base"
subvol_selector = false
autodetect_root_subvol = true

[imports.config_processing]
"ugrd.fs.btrfs" = [ "_process_root_subvol", "_process_subvol_selector" ]

[imports.build_pre]
"ugrd.fs.btrfs" = [ "autodetect_root_subvol" ]

[imports.init_mount]
"ugrd.fs.btrfs" = [ "btrfs_scan", "set_root_subvol", "select_subvol" ]

[import_order.before]
btrfs_scan = ["set_root_subvol", "mount_root"]
set_root_subvol = ["select_subvol", "mount_root"]
select_subvol = "mount_root"

[import_order.after]
mount_root = ["btrfs_scan"]

# Custom parameters
[custom_parameters]
_base_mount_path = "Path"  # Set the mount point for the root filesystem when used to check for subvols
root_subvol = "str"  # Set the default btrfs subvolume for the root filesystem
subvol_selector = "bool"  # Select a btrfs subvolume for the root partition at runtime
autodetect_root_subvol = "bool"  # Automatically detect the root subvolume
