binaries = [ "btrfs" ]
kmod_init = "btrfs"

_base_mount_path = "/mnt/root_base"
subvol_selector = false
autodetect_root_subvol = true

[imports.config_processing]
"ugrd.fs.btrfs" = [ "_process_root_subvol", "_process_subvol_selector" ]

[imports.build_pre]
"ugrd.fs.btrfs" = [ "autodetect_root_subvol" ]

[imports.init_premount]
"ugrd.fs.btrfs" = [ "btrfs_scan", "set_root_subvol", "select_subvol" ]

# Custom parameters
[custom_parameters]
_base_mount_path = "Path"  # Set the mount point for the root filesystem when used to check for subvols
root_subvol = "str"  # Set the default btrfs subvolume for the root filesystem
subvol_selector = "bool"  # Select a btrfs subvolume for the root partition at runtime
autodetect_root_subvol = "bool"  # Automatically detect the root subvolume
