mknod_cpio = true
cpio_compression = "xz"
cpio_rotate = true

[imports.config_processing]
"ugrd.fs.cpio" = [ "_process_out_file" ]

[imports.pack]
"ugrd.fs.cpio" = [ "make_cpio" ]

[custom_parameters]
out_file = "str"  # The name of the cpio file to create.
cpio_rotate = "bool"  # makes a .old backup of the cpio file if it already exists.
mknod_cpio = "bool"  # When enabled, mknod is not used to create device nodes, they are just created in the cpio.
cpio_compression = "str"  # The compression method to use for the cpio file. Currently, only xz is supported.
