modules = ["ugrd.fs.overlayfs"]

squashfs_image = 'image.squashfs'
hostonly = false

kmod_init = ['hfsplus', 'nls_utf8', 'squashfs', 'isofs', 'loop']
run_dirs = ['livecd']

test_copy_config = ["squashfs_image", "livecd_label"]

[imports.build_pre]
"ugrd.fs.livecd" = ["generate_livecd_mount", "set_squashfs_mount"]

[custom_parameters]
squashfs_image = "Path"  # the path to the squashfs image (at runtime)
livecd_label = "str"  # The label of the livecd
