modules = ["ugrd.fs.overlayfs"]

squashfs_image = 'image.squashfs'
lowerdir = "/run/squashfs"
hostonly = false

kmod_init = ['hfsplus', 'nls_utf8', 'squashfs', 'isofs', 'loop']

[imports.build_pre]
"ugrd.fs.livecd" = ["generate_livecd_mount"]

[imports.init_mount]
"ugrd.fs.livecd" = ["mount_squashfs"]

[masks]
init_mount = "mount_cmdline_root"  # Don't use the normal mount process
build_tasks = "export_mount_info"
functions = "mount_root"

[custom_parameters]
squashfs_image = "Path"  # the path to the squashfs image (at runtime)
livecd_label = "str"  # The label of the livecd
