binaries = [
  "lsblk",
  "blkid",
  "mount",
  "sleep",
  "umount",
]

mount_wait = false
autodetect_root = true
autodetect_root_luks = true
late_fstab = "/etc/fstab.late"

[imports.config_processing]
"ugrd.fs.mounts" = [ "_process_mounts_multi", "_process_late_mounts_multi", "_process_mount_timeout" ]

[imports.build_pre]
"ugrd.fs.mounts" = [ "autodetect_root", "autodetect_root_luks" ]

[imports.build_final]
"ugrd.fs.mounts" = [ "generate_fstab", "generate_late_fstab"]

[imports.init_pre]
"ugrd.fs.mounts" = [ "mount_base" ]

[imports.init_early]
"ugrd.fs.mounts" = [ "export_mount_info", "mount_fstab" ]

[imports.init_main]
"ugrd.fs.mounts" = [ "remake_mountpoints" ]

[imports.init_clean]
"ugrd.fs.mounts" = [ "clean_mounts" ]

[imports.init_mount]
"ugrd.fs.mounts" = [ "mount_root", "mount_late_fstab" ]

[imports.functions]
"ugrd.fs.mounts" = [ "clean_mounts", "_mount_fail" ]

[custom_parameters]
mounts = "dict"  # Add the mounts property, used to define the mounts to be made in the fstab
late_mounts = "dict"  # Like mounts, but run after the root is mounted
late_fstab = "str"  # The path to the late_fstab file
mount_wait = "bool"  # Add the mount_wait property, if defined, user input will be required before attempting to mount entries
mount_timeout = "float"  # Add the mount_timeout property, used to define the timeout for mount_wait
mount_cmd = "str"  # The mount command called by mount_root, can be overridden
autodetect_root = "bool"  # Add the autodetect_root property, if defined, the root mount will be autodetected
autodetect_root_luks = "bool"  # Whether or not to try to autodetect LUKS partitions


# Define the base of the root mount
[mounts.root]
skip_unmount = true
destination = "/mnt/root"
options = ['ro']

# Define the default mounts
# The format is mounts.mount where the mount is the name of the mount
# Alternatively, the destination option can be used to define the mount point

[mounts.proc]
type = "proc"
path = "proc"
options = ['nodev', 'noexec', 'nosuid']
base_mount = true

[mounts.sys]
type = "sysfs"
path = "sysfs"
options = ['nodev', 'noexec', 'nosuid']
base_mount = true

[mounts.dev]
type = "devtmpfs"
path = "devtmpfs"
options = ['nosuid', 'mode=0755']
base_mount = true
skip_unmount = true

[mounts.run]
type = "tmpfs"
path = "tmpfs"
base_mount = true
