kmod_init = ["overlay"]
run_dirs = ["upperdir", "workdir", "lowerdir"]

[imports.build_pre]
"ugrd.fs.overlayfs" = ["update_root_lowerdir"]

[imports.init_mount]
"ugrd.fs.overlayfs" = ["mount_overlayfs"]

[import_order.after]
"mount_overlayfs" = ["mount_root"]
