cmdline_strings = [ "resume" ]
cmdline_bools = [ "noresume" ]

[imports.init_early] 
"ugrd.fs.resume" = [ "handle_resume" ]

[custom_parameters]
safe_resume = "bool"  # Fail if resume is not possible
