modules = ['ugrd.fs.cpio']
paths = ['dev', 'sys', 'proc']


binaries = ['halt', 'shutdown', 'ls', 'top', 'ps']
shebang = "#!/bin/bash"
test_image_size = 16

banner = 'echo "SUCCESS"'

[masks]
pack = "make_cpio"

[imports.pack]
"ugrd.fs.test_image" = ["make_test_image"]

[custom_parameters]
shebang = "str"  # Add the shebang property, because the test mode disables the base module
test_kernel = "Path"  # Define the kernel to use for the test image
test_image_size = "int"  # Define the size of the test image in MiB
mounts = "dict"  # We only need the mounts dict, not the whole module
