binaries = [ "cryptsetup", "mkfifo", "rm" ]

paths = [ "run" ]

_kmod_depend = [ "dm_crypt", "crc32c" ]

cryptsetup_retries = 5
cryptsetup_key_type = "keyfile"

[imports.config_processing]
"ugrd.crypto.cryptsetup" = [ "_process_cryptsetup_multi", "_process_cryptsetup_key_types_multi" ]

[imports.init_pre]
"ugrd.crypto.cryptsetup" = [ "configure_library_dir" ]

[imports.init_early]
"ugrd.crypto.cryptsetup" = [ "get_crypt_sources", "make_key_pipes" ]

[imports.init_late]
"ugrd.crypto.cryptsetup" = [ "crypt_init" ]

[imports.build_pre]
"ugrd.crypto.cryptsetup" = [ "find_libgcc" ]

[cryptsetup_key_types.keyfile]
key_command = "cat {key_file} >"

[custom_parameters]
cryptsetup = "dict"  # Dict of cryptsetup volume to be unlocked, keyed by mapped device name
cryptsetup_key_type = "str"  # The default key type to use for unlocking devices
cryptsetup_key_types = "dict"  # Dict containing key types and their associated mount commands
cryptsetup_retries = "int"  # Number of times to retry unlocking a device
