modules = [ "ugrd.base.console", "ugrd.crypto.cryptsetup" ]

binaries = [ "gpg", "gpg-agent", "gpgconf", "gpg-connect-agent", "pinentry-tty" ]
paths = [ "usr/bin" ]

# Define the primary console
primary_console = "tty0"

[cryptsetup_key_types.gpg]
key_command = "gpg --decrypt {key_file} >"

[console.tty0]
type = "tty"

[symlinks.pinentry]
source = "/usr/bin/pinentry-tty"
target = "/usr/bin/pinentry"

[imports.init_early]
"ugrd.crypto.gpg" = [ "start_agent" ]

[custom_parameters]
gpg_agent_args = "NoDupFlatList"  # Arguments to be passed to the gpg-agent

