binaries = [ "ln", "gpg", "gpg-agent", "gpg-connect-agent", "pinentry-tty", "tty" ]
paths = [ "usr/bin" ]

# GPG works best under agetty for input
depends = [ "ugrd.base.serial" ]
primary_console = "tty0"

[imports.init_pre]
"ugrd.crypto.gpg" = [ "symlink_pinentry" ]

[imports.init_main]
"ugrd.crypto.gpg" = [ "start_agent" ]

[serial.tty0]
type = "tty"

