modules = [ "ugrd.base.console" ]

binaries = [ "gpg", "gpg-agent", "gpg-connect-agent", "pinentry-tty" ]
paths = [ "usr/bin" ]

# Define the primary console
primary_console = "tty0"

[console.tty0]
type = "tty"

[symlinks.pinentry]
source = "/usr/bin/pinentry-tty"
target = "/usr/bin/pinentry"

[imports.init_main]
"ugrd.crypto.gpg" = [ "start_agent" ]

