modules = [ "ugrd.crypto.gpg" ]

binaries = [ "/usr/libexec/scdaemon" ]

_kmod_depend = "uhid"

[cryptsetup_key_types.gpg]
reset_command = "gpgconf --reload scdaemon && gpg --card-status"

[custom_parameters]
sc_public_key = "str"  # The path to the public key to import

[imports.build_pre]
"ugrd.crypto.smartcard" = [ "fetch_keys" ]

[imports.init_early]
"ugrd.crypto.smartcard" = [ "import_keys" ]

[imports.init_main]
"ugrd.crypto.smartcard" = [ "check_card" ]

