modules = [ "ugrd.crypto.gpg" ]

binaries = [ "/usr/libexec/scdaemon" ]

_kmod_depend = "uhid"

[custom_parameters]
sc_public_key = "str"  # The path to the public key to import

[imports.build_pre]
"ugrd.crypto.smartcard" = [ "fetch_keys" ]

[imports.init_main]
"ugrd.crypto.smartcard" = [ "import_keys", "check_card" ]

