# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install system deps
      run: |
        sudo apt update
        sudo apt install -y pax-utils
        
    - name: Install dependencies
      run: |
        sudo PATH=$PATH python -m pip install --upgrade pip
        git clone https://github.com/desultory/zenlib
        git clone https://github.com/desultory/pycpio
        sudo PATH=$PATH pip install --break ./zenlib
        sudo PATH=$PATH pip install --break ./pycpio
        sudo PATH=$PATH pip install --break .
    - name: Test fullauto.toml
      run: |
        ls /boot
        sudo PATH=$PATH ugrd -c tests/fullauto.toml
